---
- name: Copy backup check entry point
  template:
    src: entrypoint.sh
    dest: "{{ duplicity_backup_check_dir }}.sh"
    mode: 0755
  delegate_to: "{{ duplicity_test_backup_host }}"
  run_once: true

- name: Create backup check directory
  file:
    state: directory
    path: "{{ duplicity_backup_check_dir }}"
  delegate_to: "{{ duplicity_test_backup_host }}"
  run_once: true

- name: Create host backup check directory
  file:
    state: directory
    path: "{{ duplicity_backup_check_dir }}/{{ inventory_hostname }}"

- name: Create backup check configs
  copy:
    src: "{{ item }}"
    dest: "{{ duplicity_backup_check_dir }}/{{ inventory_hostname }}/"
    owner: root
    group: root
    mode: 0755
  with_fileglob: "configs/{{ inventory_hostname }}/duplicity_configs/*.conf"
  delegate_to: "{{ duplicity_test_backup_host }}"

- name: Copy backup verify script
  copy:
    src: "{{ item }}"
    dest: "{{ duplicity_backup_check_dir }}/{{ inventory_hostname }}/"
    mode: 0755
  delegate_to: "{{ duplicity_test_backup_host }}"
  with_fileglob: "backupScripts/*"

- name: Create backup verify main config
  template:
    src: backup_config
    dest: "{{ duplicity_backup_check_dir }}/{{ inventory_hostname }}/backupConfig"
    mode: 0755
    owner: root
    group: root
  delegate_to: "{{ duplicity_test_backup_host }}"
